services:
  vite-app:
    image: "kudo-machine:latest"
    ports:
      - "8080:8080"
      - "3000:3000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - redis
    environment:
      NODE_ENV: development

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
